version: '3' 
services:
  keycloak:
    image: jboss/keycloak:8.0.1
    container_name: "keycloak"
    volumes:
      - ./realms/:/tmp/
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-import.json -Dkeycloak.profile.feature.upload_scripts=enabled 
    ports:
      - 33174:8080
    expose:
      - 33174
    networks:
      - ed-order-network
networks:
  ed-order-network:
    external: false 