version: '3' 
services:
  db: 
    image: postgres:alpine
    container_name: "db_app"
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: 'order_db'
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - network-internal
  keycloak:
    restart: always
    image: jboss/keycloak:8.0.1
    container_name: "keycloak"
    volumes:
      - ./realms/:/tmp/
    # command: 
        # - "-b 0.0.0.0 -Dkeycloak.import=/tmp/realm-import.json -Dkeycloak.profile.feature.upload_scripts=enabled"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-import.json -Dkeycloak.profile.feature.upload_scripts=enabled 
    ports:
      - 33174:8080
    expose:
      - 33174
    networks:
      - network-internal
networks:
  network-internal:
    external: false 